### ISSUE TITLE
Unable to create solace cloud service with ansible module solace_cloud_service 

### ISSUE THREAD

**Issue by PrakashFromBunnings** [solace-iot-team/ansible-solace-collection#30]
Hello, 

Recently we have received solace cloud instance . And we are trying to provision services via ansible . 

We do receive below error .

`
    "msg": {
        "body": {
            "errorId": "6f191d2fc255d2ca",
            "message": "An authentication error occurred.",
            "subCode": "4000_107",
            "traceId": "6f191d2fc255d2ca"
        },
        "reason": "",
        "status_code": 401
    },
    "rc": 1
`

We checked with API calls too we received similar error 

`
GET https://api.solace.cloud/api/v0/services

{
    "message": "An authentication error occurred.",
    "subCode": "4000_107",
    "errorId": "f2d8b580fa0b1f85",
    "traceId": "f2d8b580fa0b1f85"
}

`

After raising this with Solace cloud support , they mentioned to change the URL  
from 
api.solace.cloud
to 
api.solacecloud.com.au 

Wondering how do we change this in ansible collection we use 
https://solace-iot-team.github.io/ansible-solace-collection/modules/solace_cloud_service.html
https://galaxy.ansible.com/solace/pubsub_plus

**Comment by ricardojosegomezulmke** [comment]
the collection does currently only support the standard solace cloud url.
it is an enhancement I can look at.
But I need a login to your cloud instance - could you invite me?

**Comment by PrakashFromBunnings** [comment]
@ricardojosegomezulmke  I sent invite  to your solace email id 
![image](https://user-images.githubusercontent.com/83051828/166610973-b100dd1a-493e-4f06-982b-2b32606469b8.png)

**Comment by ricardojosegomezulmke** [comment]
included in release 1.9.2.
see: https://solace-iot-team.github.io/ansible-solace-collection/solace_cloud_modules.html

**Comment by ricardojosegomezulmke** [comment]
closing issue.
