### ISSUE TITLE
Feature request: Additional hostname to a service

### ISSUE THREAD

**Issue by mtafer** [solace-iot-team/ansible-solace-collection#33]
Hi team,
To quickly summarize our need, we need to be able to automate the creation of additional hostname of new Solace cloud service.
As far as I can see, this can be done through the Rest API URL and payload
 below:
**URL**: [https://api.solace.cloud/api/v0/serviceConnectionEndpoints/**l4a55jnrzcb**/serviceHostNames]
              **l4a55jnrzcb** being the vmrid of the broker
**Payload**: {"operation":"create","serviceHostName":"play-ric-mb-defra-aws-1"}

**Comment by ricardojosegomezulmke** [comment]
part of release 1.10.0

https://solace-iot-team.github.io/ansible-solace-collection/modules/solace_cloud_service_hostname.html
https://solace-iot-team.github.io/ansible-solace-collection/modules/solace_cloud_get_service_hostnames.html
https://solace-iot-team.github.io/ansible-solace-collection/modules/solace_cloud_service_hostnames.html

**Comment by mtafer** [comment]
Hi Ricardo, this doesn't seem to be working on version 9.13 unfortunately.
May you please reopen this issue?
