### ISSUE TITLE
Feature request: Additional hostname Configuration for a 9.13 service

### ISSUE THREAD

**Issue by alyrasmy** [solace-iot-team/ansible-solace-collection#38]
Feature request for the adding to the ansible collection the option of configuring additional hostname ( for both private and public endpoints) for a PS+ Cloud service (SolOS 9.13)

**Comment by ricardojosegomezulmke** [comment]
will be part of next release.

**Comment by ricardojosegomezulmke** [comment]
adding private hostnames is now available in release 1.10.2
closing request.
